### ISSUE TITLE
Background on the Code

### ISSUE THREAD

**Issue by RoyiAvital** [snorpey/triangulation#4]
Could you explain how do you create this effect?

Namely:
1. Blur.
2. Find Edges.
3. Etc...

Thank You.

**Comment by snorpey** [comment]
The actual triangulation of the image starts in the [process.js](https://github.com/snorpey/triangulation/blob/develop/scripts/src/process.js) in a function called [processImage](https://github.com/snorpey/triangulation/blob/develop/scripts/src/process.js#L76).

An overview what happens in there:

1. The image is put on two separate canvas elements. The image data on the first canvas is used for calculating the shape of the polygons. Several filters are applied to this canvas throughout the process. The image data on the second canvas is never changed and used for calculating the color of the polygons later.

2. The image data is [blurred](https://github.com/snorpey/triangulation/blob/develop/scripts/src/process.js#L97), using [Superfast Blur](http://quasimondo.com/BoxBlurForCanvas/FastBlurDemo.html) by @quasimondo . This blurring library may not be quite as accurate as others (Though I haven't compared it to other libraries extensively, so I might be wrong), but it is very fast, which I think is more important here.

3. A [greyscale](https://github.com/snorpey/triangulation/blob/develop/scripts/util/greyscale.js) filter is [applied](https://github.com/snorpey/triangulation/blob/develop/scripts/src/process.js#L99) to the image data

4. Edges are [detected](https://github.com/snorpey/triangulation/blob/develop/scripts/util/detect-edges.js)

5. Edge point coordinates are [calculated](https://github.com/snorpey/triangulation/blob/develop/scripts/util/get-edge-points.js) from the edges image data

6. From all edge point coordinates, a random number is [selected](https://github.com/snorpey/triangulation/blob/develop/scripts/util/get-random-vertices.js)

7. The point coordinates are [fed](https://github.com/snorpey/triangulation/blob/develop/scripts/src/process.js#L107) into @ironwallaby's [delaunay.js](https://github.com/ironwallaby/delaunay/) library, which calculates polygons based on those coordinates.

8. It [calculates](https://github.com/snorpey/triangulation/blob/develop/scripts/src/process.js#L167) the center coordinate of each polygon and looks up the color for this coordinate in the original image (the second canvas from step 1)

9. it draws the polygons on the screen

Let me know if you run into problems or if you want me to clarify anything. :-)

**Comment by snorpey** [comment]
closing this issue, please write a comment if you have further questions.

**Comment by RoyiAvital** [comment]
Hi,
This is great.

Could you link the parameters from the Online Demo to the steps you mentioned?

Thank You.

**Comment by snorpey** [comment]
@RoyiAvital i'm not completely sure i understand the question... which parameters are you referring to?
