### ISSUE TITLE
Command Line Examples

### ISSUE THREAD

**Issue by davidrenne** [snorpey/triangulation#6]
I am trying to set this up so I can call the node js build to run at the command line.  Does anyone have any ideas after I npm install to run these commands outside of the web browser?

I am sure others have the same questions and would love more examples in the readme.md.

Thank you for your time in helping me use this great tool.

**Comment by davidrenne** [comment]
@snorpey any ideas here?  I remember wasting 2 or 3 hours trying to get command line examples to work with node.js as my process cannot easily open a web browser for each image it needs to triangulate and need to make it happen on node.js using command switches.

I am starting again to try once more to get this working today, it would be great if you had any ideas to help someone out whose using your awesome project.  Maybe once I get it working I can update your documentation with a pull request to help those looking to do the same thing with a mini tutorial on calling the javascript from command line

**Comment by snorpey** [comment]
hey @davidrenne looks like i missed the notification for when you first opened the issue. sorry about that.

some time ago, i looked into making the code run on node, but i didn't get anywhere. that's mostly because i couldn't get [node-canvas](https://github.com/Automattic/node-canvas) to run properly on my machine.

but once node-canvas is properly set up, it should be possible to generate the images on the fly. if you've set up node-canvas successfully and want to give it a try, [here](https://github.com/snorpey/triangulation/blob/develop/scripts/src/process.js#L76) is probably a good place to start.

i hope this helps. let me know if you have questions about the code.

**Comment by davidrenne** [comment]
Thank you for the advice and time in writing a response.  Do know how i can get a simple javascript file (kind of like a main caller file) to use require.js so i have all the dependencies loaded so  can call that function you mentioned?

**Comment by davidrenne** [comment]
@snorpey Hey I think I have found a path to getting dependencies built out.  I basically am using grunt production but not minifying the JS using the `optimize: 'none',` on the requirejs so I can debug this stuff.

But the problem I am going to have is window/document/navigator and that function you referenced needs the canvas in the document.

Any ideas of mocking up a virtual dom around this entire process so I can create these things needed for that function to fire?  I will do some more research here on how to do virtual dom in node and wrapping that in your process.

**Comment by davidrenne** [comment]
Here's my work in progress on getting it to run from a base compile to my modified version:

https://gist.github.com/davidrenne/46482f3d14f4b9409d5f/revisions

Node is not throwing any errors now, but I need to figure out how to call a requirejs main function

Heres the install script to get things working (had to install node4 and jsdom to get a window and document)

```
wget -qO- https://deb.nodesource.com/setup_4.x | sudo bash -
sudo apt-get install --yes nodejs
npm install jsdom
```

Do you have any ideas now how how to somehow get it to take lincoln.jpg which is in the virtual window and save him off as a file?

I need to make some adjustments to simulate the export_button click event and then push the output to a new file.

I am going to take a little break and start with a fresh mind on it and read some of your source code more to figure out how to output the file to something on the file system.

**Comment by snorpey** [comment]
hey @davidrenne i just got node-canvas to work on my machine and ported the code to node. you can find it here: https://github.com/snorpey/node-triangulation (it's not super polished or anything, but it should get the job done.)

**Comment by davidrenne** [comment]
Talk about amazing free service!!!   You are a gentleman and a scholar.
Ive been banging my head all afternoon in require js hell.

I got as far as virtual dom canvas creation that was failing inside of the
function you mentioned.  Im 100% confident your new project will work for me
